---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/httpd_vars.yaml

  tasks:
    - name: Check if apache is installed
      package_facts:
        manager: 'auto'

    - name: Stop Apache service
      service:
        name: httpd
        state: stopped
      when: '"httpd" in ansible_facts.packages'
        
    - name: Delete document root
      file:
        backup:
        path: "{{ web_root_path }}"
        state: absent
      when: '"httpd" in ansible_facts.packages'

    - name: Remove Apache
      when: '"httpd" in ansible_facts.packages'
      dnf:
        name: httpd
        state: removed
        
    - name: Remove unneeded packages
      when: '"httpd" in ansible_facts.packages'
      dnf:
        autoremove: yes
        
    - name: Disable firewall rule for apache service
      firewalld:
        service: http
        zone: public
        permanent: yes
        immediate: yes
        state: disabled 
