---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled

  roles:
  - role: 'roles/apache_httpd_centos8'
