---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - ../vars/httpd_vars.yaml

  tasks:
#centos based OS version 7 stuff
    - name: Install Apache on centos major_version 8
      when: ansible_facts['distribution_major_version'] == "8"
      dnf:
        name: httpd
        state: latest
        update_cache: yes

    - name: Create document root
      file:
        path: "{{ web_root_path }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy index page
      template:
        src: "../files/index.html.jinja2"
        dest: "{{ web_root_path }}/index.html"

    - name: Enable Apache service to start on boot up
      service:
        name: httpd
        state: started

    - name: Open firewall port for apache
      ansible.posix.firewalld:
        service: "{{ http_port }}"
        state: enabled
        zone: public
        permanent: true
        immediate: true        
      
      
  handlers:
    - name: Restart apache service
      service:
        name: httpd
        state: restarted




  #   - name: Set up Apache virtualhost
  #     template:
  #       src: "files/apache.conf.j2"
  #       dest: "/etc/apache2/sites-available/{{ http_conf }}"

  #   - name: Enable new site
  #     shell: /usr/sbin/a2ensite {{ http_conf }}
  #     notify: Reload Apache

  #   - name: Disable default Apache site
  #     shell: /usr/sbin/a2dissite 000-default.conf
  #     when: disable_default
  #     notify: Reload Apache

  #   - name: Open firewall port for apache
  #     ansible.posix.firewalld:
  #       service: "{{ http_port }}"
  #       state: enabled
  #       permanent: true
  #       immediate: true

  # handlers:
  #   - name: Reload Apache
  #     service:
  #       name: httpd
  #       state: reloaded

  #   - name: Restart Apache
  #     service:
  #       name: httpd
  #       state: restarted
