---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - ../vars/httpd_vars.yaml

  tasks:
    - name: Install Apache on centos major_version 8
      when: ansible_facts['distribution_major_version'] == "8"
      dnf:
        name: httpd
        state: latest
        update_cache: yes

    - name: Create document root
      file:
        path: "{{ web_root_path }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy index page
      template:
        src: "../files/index.html.jinja2"
        dest: "{{ web_root_path }}/index.html"

    - name: Enable Apache service to start on boot up
      service:
        name: httpd
        state: started
        
    - name: Create firewall rule for apache service
      firewalld:
        service: http
        zone: public
        permanent: yes
        immediate: yes
        state: enabled  
      
  handlers:
    - name: Restart apache service
      service:
        name: httpd
        state: restarted
