---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - ../vars/httpd_vars.yaml

  tasks:
    #centos based OS version 7 stuff
    - name: Remove Apache on centos major_version 8
      when: ansible_facts['distribution_major_version'] == "8"
      dnf:
        name: httpd
        state: removed
        
    - name: Remove unneeded packages on centos major_version 8
      when: ansible_facts['distribution_major_version'] == "8"
      dnf:
        autoremove: yes

    - name: Create document root
      file:
        path: "{{ web_root_path }}"
        state: absent

    - name: Enable Apache service to start on boot up
      service:
        name: httpd
        state: stopped
        
    - name: Disable firewall rule for apache service
      firewalld:
        service: http
        zone: public
        permanent: yes
        immediate: yes
        state: disabled 
