---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - ../vars/httpd_vars.yaml

  tasks:
  - name: check if splash is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*splash'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: insert splash if missing
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 splash"'
    when: grub_cmdline_check.found == 0
    notify: update grub




  - lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* audit)\"[^\"]+)(\".*)'
      line: '\1 audit=1\2'

  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ option }}={{ value }}\2'
  vars:
    option: audit
    value: 1


- name: I/O scheduler at boot time (add)
  replace: name={{grub_cfg}}
           regexp="^(\s*linux(?!.* elevator=).*)"
           replace="\1 elevator=deadline"

- name: I/O scheduler at boot time (replace)
  replace: name={{grub_cfg}}
           regexp="^(\s*linux.*? elevator=)(?!deadline)(\S*)(.*)"
           replace="\1deadline\3"
