---
- hosts: centos_webservers
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: ensure file exists key-value.cfg
    copy:
      content: ""
      dest: key-value.cfg
      force: no
      group: ansible
      owner: ansible
      mode: 0644

  - name: populate key-value.cfg file
    lineinfile:
      path: ./key-value.cfg
      state: present
      line: "{{ item }}"
    with_items:
    - 'hello world'
    - '# spacing variations'
    - 'thiskey1=thisvalue1'
    - 'thiskey2 = thisvalue2'
    - 'thiskey3 =thisvalue3'
    - '# comment variations'
    - '#thiskey4 = thisvalue4'
    - '# thiskey5 = thisvalue5'
    - '## thiskey6 = thisvalue6'
     

  - name: Replace values in config file
    lineinfile:
      state: present
      path: ./key-value.cfg
      regexp: '^[# ]*{{ item.search }}\s*=\s*'
      line: '{{ item.replace }}'
    with_items:
      - { search: 'thiskey1', replace: 'thiskey1 = NEWthisval1' }
      - { search: 'thiskey2', replace: 'thiskey2 = NEWthisval2' }
      - { search: 'thiskey3', replace: 'thiskey3 = NEWthisval3' }
      - { search: 'thiskey4', replace: 'thiskey4 = NEWthisval4' }
      - { search: 'thiskey5', replace: 'thiskey5 = NEWthisval5' }
      - { search: 'thiskey6', replace: 'thiskey6 = NEWthisval6' }
      # keys that do not exist get created
      - { search: 'thiskey7', replace: 'thiskey7 = INSthisnewval7' }


  - name: Replace the world
    lineinfile:
      dest: ./key-value.cfg
      regexp: '^(hello)world$'
      line: '\g<1>030'
      backrefs: true